### ISSUE TITLE
CI: improve build CI with a step to upload into workflow artifacts

### ISSUE THREAD

**Issue by yarikoptic** [con/opfvta-replication-2023#23]
chatgpt

```yaml
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: paper-pdf
          path: paper/source/paper.pdf
```

we do a lot of such things within datalad/git-annex, e.g. https://github.com/datalad/git-annex/actions/runs/5538542139 has it at the bottom

![image](https://github.com/con/opfvta-replication-2023/assets/39889/732e0a9f-7f9c-4690-91ac-da977616a27a)
